server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: jj20020813
  redis:
    host: 127.0.0.1
    port: 6379
    password: jj20020813
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # 生产者：把我们要发的 JSON 字符串当成普通 String 处理
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 确认机制：all 代表所有的副本都收到消息才算成功，保证消息绝对不丢
      acks: all
    consumer:
      group-id: seckill-group
      # 【关键】：关闭自动提交，防止业务报错但消息被当成已消费
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 【关键】：设置手动调用 ack.acknowledge() 时立即提交
      ack-mode: manual_immediate
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug